using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ResimamisBackend.Migrations
{
    /// <inheritdoc />
    public partial class Visita : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""VISITA"" (
    ""idVisita"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""idBebe"" integer NOT NULL,
    ""nombreVisitante"" text NOT NULL,
    ""familiar"" text NOT NULL,
    ""fechaHoraVisita"" timestamp without time zone NOT NULL,
    ""observacion"" text NULL,
    ""documentoVisitante"" integer NULL,
    ""telefonoVisitante"" bigint NULL,
    ""Activa"" boolean NOT NULL DEFAULT TRUE,
    ""fechaRegistro"" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
");

            migrationBuilder.Sql(@"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    INNER JOIN pg_class rel ON rel.oid = c.conrelid
    WHERE rel.relname = 'VISITA'
      AND c.contype = 'f'
      AND c.conname = 'FK_VISITA_BEBE_idBebe'
  ) THEN
    ALTER TABLE ""VISITA""
      ADD CONSTRAINT ""FK_VISITA_BEBE_idBebe""
      FOREIGN KEY (""idBebe"") REFERENCES ""BEBE"" (""ID"")
      ON DELETE RESTRICT;
  END IF;
END $$;
");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_VISITA_idBebe"" ON ""VISITA"" (""idBebe"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""VISITA"";");
        }
    }
}
