// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResimamisBackend.Datos;

#nullable disable

namespace ResimamisBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResimamisBackend.Datos.AMBITO", b =>
                {
                    b.Property<int>("idAmbito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idAmbito"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idAmbito");

                    b.ToTable("AMBITO");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.ASIGNACION", b =>
                {
                    b.Property<int>("idAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idAsignacion"));

                    b.Property<string>("comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaHoraAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("idBebe")
                        .HasColumnType("integer");

                    b.Property<int>("idEstado")
                        .HasColumnType("integer");

                    b.Property<int?>("idTarea")
                        .HasColumnType("integer");

                    b.Property<int>("idVoluntaria")
                        .HasColumnType("integer");

                    b.HasKey("idAsignacion");

                    b.HasIndex("idBebe");

                    b.HasIndex("idEstado");

                    b.HasIndex("idTarea");

                    b.HasIndex("idVoluntaria");

                    b.ToTable("ASIGNACION");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.ASISTENCIA", b =>
                {
                    b.Property<int?>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("IdAsistencia"));

                    b.Property<DateTime?>("FechaHoraIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdHorario")
                        .HasColumnType("integer");

                    b.Property<int?>("IdVoluntaria")
                        .HasColumnType("integer");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdVoluntaria");

                    b.ToTable("ASISTENCIA");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.BEBE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("DiagnosticoEgreso")
                        .HasColumnType("text");

                    b.Property<string>("DiagnosticoIngreso")
                        .HasColumnType("text");

                    b.Property<int?>("Dni")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaIngresoNEO")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("integer");

                    b.Property<int?>("IdMadre")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSala")
                        .HasColumnType("integer");

                    b.Property<string>("LugarNacimiento")
                        .HasColumnType("text");

                    b.Property<decimal?>("PesoAlta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PesoDiaAbrazos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PesoIngresoNEO")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PesoNacimiento")
                        .HasColumnType("numeric");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<string>("apellido")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdMadre");

                    b.HasIndex("IdSala");

                    b.ToTable("BEBE");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.DETALLEASIGNACION", b =>
                {
                    b.Property<int>("idDetalleAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDetalleAsignacion"));

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("fechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fechaRetiro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idAsignacion")
                        .HasColumnType("integer");

                    b.Property<int>("idInsumo")
                        .HasColumnType("integer");

                    b.Property<string>("nombreInsumo")
                        .HasColumnType("text");

                    b.HasKey("idDetalleAsignacion");

                    b.HasIndex("idAsignacion");

                    b.HasIndex("idInsumo");

                    b.ToTable("DETALLEASIGNACION");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.DIA", b =>
                {
                    b.Property<int>("IdDia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDia"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDia");

                    b.ToTable("DIA");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.ESTADO", b =>
                {
                    b.Property<int>("idEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEstado"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idAmbito")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idEstado");

                    b.HasIndex("idAmbito");

                    b.ToTable("ESTADO");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.HORARIO", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHorario"));

                    b.Property<TimeSpan>("HoraIngreso")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("interval");

                    b.Property<int>("IdDia")
                        .HasColumnType("integer");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdHorario");

                    b.ToTable("HORARIO");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.INSUMO", b =>
                {
                    b.Property<int>("idInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idInsumo"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("stockActual")
                        .HasColumnType("integer");

                    b.Property<int>("stockMaximo")
                        .HasColumnType("integer");

                    b.Property<int>("stockMinimo")
                        .HasColumnType("integer");

                    b.HasKey("idInsumo");

                    b.ToTable("INSUMO");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.LOCALIDAD", b =>
                {
                    b.Property<int>("idLocalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idLocalidad"));

                    b.Property<int>("idProvincia")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idLocalidad");

                    b.ToTable("LOCALIDAD");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.MADRE", b =>
                {
                    b.Property<int>("IdMadre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMadre"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CantidadHijos")
                        .HasColumnType("integer");

                    b.Property<long>("Celular")
                        .HasColumnType("bigint");

                    b.Property<int>("Dni")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Localidad")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoAbrazo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMadre");

                    b.ToTable("MADRE");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.MOVIMIENTOSTOCK", b =>
                {
                    b.Property<int>("idMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idMovimiento"));

                    b.Property<int?>("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("esEntrada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("fechaMovimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("idBebe")
                        .HasColumnType("integer");

                    b.Property<int>("idInsumo")
                        .HasColumnType("integer");

                    b.Property<int?>("idProveedor")
                        .HasColumnType("integer");

                    b.Property<int?>("idVoluntaria")
                        .HasColumnType("integer");

                    b.Property<string>("observacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idMovimiento");

                    b.ToTable("MOVIMIENTOSTOCK");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.PROVEEDOR", b =>
                {
                    b.Property<int>("idProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idProveedor"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idProveedor");

                    b.ToTable("PROVEEDOR");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.ROL", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("ROL");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.SALA", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSala"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSala");

                    b.ToTable("SALA");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.TAREA", b =>
                {
                    b.Property<int>("idTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTarea"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idTarea");

                    b.ToTable("TAREA");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.USUARIO", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Dni")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdVoluntaria")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.VOLUNTARIA", b =>
                {
                    b.Property<int>("IdVoluntaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVoluntaria"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Celular")
                        .HasColumnType("bigint");

                    b.Property<int>("Dni")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("integer");

                    b.Property<int?>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdVoluntaria");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdRol");

                    b.ToTable("VOLUNTARIA");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.VOLUNTARIAHORARIO", b =>
                {
                    b.Property<int>("IdHorarioVoluntaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHorarioVoluntaria"));

                    b.Property<int>("IdHorario")
                        .HasColumnType("integer");

                    b.Property<int>("IdVoluntaria")
                        .HasColumnType("integer");

                    b.HasKey("IdHorarioVoluntaria");

                    b.ToTable("VOLUNTARIAHORARIO");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.ASIGNACION", b =>
                {
                    b.HasOne("ResimamisBackend.Datos.BEBE", "bebe")
                        .WithMany("Asignaciones")
                        .HasForeignKey("idBebe");

                    b.HasOne("ResimamisBackend.Datos.ESTADO", "estado")
                        .WithMany("Asignaciones")
                        .HasForeignKey("idEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResimamisBackend.Datos.TAREA", "tarea")
                        .WithMany("Asignaciones")
                        .HasForeignKey("idTarea");

                    b.HasOne("ResimamisBackend.Datos.VOLUNTARIA", "voluntaria")
                        .WithMany("Asignaciones")
                        .HasForeignKey("idVoluntaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bebe");

                    b.Navigation("estado");

                    b.Navigation("tarea");

                    b.Navigation("voluntaria");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.ASISTENCIA", b =>
                {
                    b.HasOne("ResimamisBackend.Datos.VOLUNTARIA", "Voluntaria")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdVoluntaria");

                    b.Navigation("Voluntaria");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.BEBE", b =>
                {
                    b.HasOne("ResimamisBackend.Datos.ESTADO", "Estado")
                        .WithMany("Bebes")
                        .HasForeignKey("IdEstado");

                    b.HasOne("ResimamisBackend.Datos.MADRE", "Madre")
                        .WithMany("Bebe")
                        .HasForeignKey("IdMadre");

                    b.HasOne("ResimamisBackend.Datos.SALA", "Sala")
                        .WithMany()
                        .HasForeignKey("IdSala");

                    b.Navigation("Estado");

                    b.Navigation("Madre");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.DETALLEASIGNACION", b =>
                {
                    b.HasOne("ResimamisBackend.Datos.ASIGNACION", "asignacion")
                        .WithMany("detallesAsignacion")
                        .HasForeignKey("idAsignacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResimamisBackend.Datos.INSUMO", "insumo")
                        .WithMany("detalles")
                        .HasForeignKey("idInsumo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asignacion");

                    b.Navigation("insumo");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.ESTADO", b =>
                {
                    b.HasOne("ResimamisBackend.Datos.AMBITO", "ambito")
                        .WithMany("estados")
                        .HasForeignKey("idAmbito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ambito");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.VOLUNTARIA", b =>
                {
                    b.HasOne("ResimamisBackend.Datos.ESTADO", "Estado")
                        .WithMany("Voluntarias")
                        .HasForeignKey("IdEstado");

                    b.HasOne("ResimamisBackend.Datos.ROL", "RolInfo")
                        .WithMany("Voluntarias")
                        .HasForeignKey("IdRol");

                    b.Navigation("Estado");

                    b.Navigation("RolInfo");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.AMBITO", b =>
                {
                    b.Navigation("estados");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.ASIGNACION", b =>
                {
                    b.Navigation("detallesAsignacion");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.BEBE", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.ESTADO", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Bebes");

                    b.Navigation("Voluntarias");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.INSUMO", b =>
                {
                    b.Navigation("detalles");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.MADRE", b =>
                {
                    b.Navigation("Bebe");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.ROL", b =>
                {
                    b.Navigation("Voluntarias");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.TAREA", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("ResimamisBackend.Datos.VOLUNTARIA", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Asistencias");
                });
#pragma warning restore 612, 618
        }
    }
}
